// Generated by Selenium IDE
package SeleniumPack;
//import java.util.HashMap;
//import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestCalorieCalculatorTest {
  private WebDriver driver;
  //private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void TestCalorieCalculator() {
    driver.get("https://www.calculator.net/calorie-calculator.html");
    driver.manage().window().setSize(new Dimension(658, 680));
    driver.findElement(By.id("cage")).click();
    driver.findElement(By.id("cage")).sendKeys("45");
    driver.findElement(By.cssSelector("td > .cbcontainer:nth-child(2) > .rbmark")).click();
    driver.findElement(By.id("cheightmeter")).click();
    driver.findElement(By.id("cheightmeter")).click();
    driver.findElement(By.id("cheightmeter")).click();
    driver.findElement(By.id("cheightmeter")).click();
    driver.findElement(By.id("cheightmeter")).sendKeys("168");
    driver.findElement(By.cssSelector("td:nth-child(2) > input:nth-child(2)")).click();
  }
}
